# -*- coding: utf-8 -*-
"""Course Project Backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMmWR81Evr4kgbQuBxMUd_4VaAtVWRZ2
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')

conn.executescript("""
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    price REAL NOT NULL,
    image_url TEXT,
    category_id INTEGER,
    seller_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (seller_id) REFERENCES users (id)
);

CREATE TABLE orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    customer_id INTEGER,
    status TEXT DEFAULT 'pending',
    FOREIGN KEY (customer_id) REFERENCES users (id)
);

CREATE TABLE order_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER,
    FOREIGN KEY (order_id) REFERENCES orders (id),
    FOREIGN KEY (product_id) REFERENCES products (id)
);
""")

conn.executescript('''
INSERT INTO categories (name) VALUES
('Accessories'),
('Art & Collectibles'),
('Baby'),
('Bags & Purses'),
('Bath & Beauty'),
('Books, Movies & Music'),
('Clothing'),
('Craft Supplies & Tools'),
('Electronics & Accessories'),
('Gifts'),
('Home & Living'),
('Jewelry'),
('Paper & Party Supplies'),
('Pet Supplies'),
('Shoes'),
('Toys & Games'),
('Weddings');
''')

conn.execute('''
INSERT INTO users (username, email, password_hash)
VALUES ('eg150', 'edwingeorge240@gmail.com', '1234');
''')

conn.executescript('''
INSERT INTO products (title, description, price, category_id, seller_id, image_url) VALUES
('Necklace', '14K Solid Gold Initial Necklace with Birthstone, Custom Initial Necklace', 29.90, 12, 1, 'https://i.etsystatic.com/46113998/r/il/f2fd60/5275681512/il_794xN.5275681512_eigm.jpg'),
('Canvas Bag', 'Small Canvas Signature Baguette Bag - Handbag and Shoulder Night Shoulder Bag - Statement Small Bag', 215.00, 4, 1, 'https://i.etsystatic.com/39572571/r/il/7e969c/5395850912/il_794xN.5395850912_p52v.jpg'),
('Bath Bombs', 'Bath Bomb Spa Gift Set of 12, Natural Aromatherapy Botanical Spa Bath Bombs', 21.00, 5, 1, 'https://i.etsystatic.com/10810145/r/il/7b9630/5761295042/il_794xN.5761295042_1hj4.jpg');
''')

user_id = conn.execute("SELECT id FROM users WHERE username = 'eg150';").fetchone()[0]
conn.execute("INSERT INTO orders (customer_id) VALUES (?);", (user_id,))

order_id = conn.execute("SELECT id FROM orders WHERE customer_id = ? ORDER BY order_date DESC;", (user_id,)).fetchone()[0]
product_ids = conn.execute("SELECT id FROM products WHERE category_id = (SELECT id FROM categories WHERE name = 'Bath & Beauty');").fetchall()

for product_id in product_ids:
    conn.execute("INSERT INTO order_items (order_id, product_id, quantity) VALUES (?, ?, ?);", (order_id, product_id[0], 1))

conn.commit()


display_queries = [
    "SELECT * FROM users;",
    "SELECT * FROM categories;",
    "SELECT * FROM products;",
    "SELECT * FROM orders;",
    "SELECT * FROM order_items;"
]

for query in display_queries:
    result = pd.read_sql_query(query, conn)
    print(result)

conn.close()